### PR TITLE
run tests with miniracer gem

### PR DESCRIPTION
**Pull request by rmosolgo**
I'm interested in trying out this new Ruby-JS bridge: https://github.com/discourse/mini_racer

### CODE REVIEW

**Comment by thedrow** [comment]
Looks really good!

**Comment by krzysiek1507** [comment]
@rmosolgo `gemfiles/rails_5_mini_racer.gemfile` is missing in `gemfiles` section ;)

**Comment by krzysiek1507** [comment]
@rmosolgo what about this?

**Comment by rmosolgo** [comment]
😁

**Pull request merged**
