### PR TITLE
Let’s test against Rails 5.2

### PR DESCRIPTION
**Pull request by ttanimichi**

### CODE REVIEW

**Comment by ttanimichi** [comment]
The travis build was failed, but it has nothing to do with this patch.
https://travis-ci.org/reactjs/react-rails/builds/375740147

**Comment by BookOfGreg** [comment]
@ttanimichi You have been helping around here a lot lately. Would you consider helping as a maintainer?
Same vein as #785

**Comment by ttanimichi** [comment]
@BookOfGreg Thank you for the offer! I’d be glad to become a maintainer.

**Comment by BookOfGreg** [comment]
@zpao Can you please grant ttanimichi member to the reactjs rails team?

**Comment by zpao** [comment]
👍 all set! Thanks for helping out @ttanimichi!

**Pull request merged**
