### PR TITLE
Expose the React mounting and un-mounting mechanisms

### PR DESCRIPTION
**Pull request by robrobbins**
Re: #116 

This is my initial commit, all within a `react_ujs_p.js` file so that we may discuss it further. I'll get to the tests tomorrow, though I expect the existing to pass. I do need to write a few new ones.

Currently I am using this modded version is a non-turbolinks SPA and it works fine.

### CODE REVIEW

**Comment by rmosolgo** [comment]
@zpao any objections to going forward like that ^^ ?

@robrobbins  He said he'd be busy so if we don't hear from him in 48 hours, I think we should take that as agreement :)

**Comment by robrobbins** [comment]
sure. i'll get on it later today then

**Comment by zpao** [comment]
:+1: sounds good! Sorry for the delay, this project is unfortunately low on the priority list with everything else :(

**Comment by robrobbins** [comment]
Done

**Comment by rmosolgo** [comment]
:+1: you're a good man @robrobbins 

dropped this in locally just to make double-sure & looks good to me

**Comment by robrobbins** [comment]
:+1: Thanks

Did the same, been using it on the redesign of a big commercial app. Doing fine.

:shipit:

**Comment by rmosolgo** [comment]
:money_with_wings:

**Comment by jmagoon** [comment]
This is a great addition. Quick question, is there any reason to leave the JSON inside of the data-react-props attribute after you've called React.render()? My current application renders about 5000 objects to the page, and having those sit in the attribute causes the developer console to crawl and sometimes crash.

My current approach is just to call node.removeAttribute(PROPS_ATTR) right after the render step in the MountComponents function. Is there a reason to keep that attribute around?

**Comment by rmosolgo** [comment]
@jmagoon I'd be in favor of that change. 

The only downside I can think of is that components wouldn't be re-mountable. But, is that something that  matters? Does anyone depend on that?

Actually, I think I do that sometimes: arbitrarily fire `page:change` (faking the Turbolinks event) in order to mount components in a just-loaded modal. At present, it just doesn't matter because it re-mounts with the same `data-react-class` and `data-react-props` (and React doesn't end up doing anything to the DOM). So maybe if you removed `data-react-props`, you could also remove `data-react-class`, so that calling `ReactRailsUJS.mountComponents()` would just miss those things all together.

Oh wait, that wouldn't work because `unmountComponents` depends on that `data-react-class` attribute. :S

Anyways, I'm open to something like that ^^, especially if we could get something like #91 worked in. (Then I could stop my stupid hack for mounting new components!)

**Comment by robrobbins** [comment]
i can look into it

**Comment by rmosolgo** [comment]
@jmagoon Turns out we need to keep those props in the DOM to support turbolinks, see #159

**Pull request merged**
