### PR TITLE
Add documentation for controller component rendering

### PR DESCRIPTION
**Pull request by garbles**
As per discussion in the [pull request for this feature](https://github.com/reactjs/react-rails/pull/329#issuecomment-136419566). :neckbeard: 

/cc @rmosolgo

### CODE REVIEW

**Comment by borisrorsvort** [comment]
Maybe we should say if there is a layout option or not :wink:

**Comment by garbles** [comment]
@borisrorsvort thought about that, but I thought that stating `The component will be rendered in place of yield.` would be enough. As a renderer, it accepts all of the usual options for rendering a view including `layout`.

Could change this to `The component will be rendered in place of yield in the layout` if we think that it makes things slightly more clear.

**Comment by borisrorsvort** [comment]
Or "it behaves the same as normal render and his usual options"

**Comment by rmosolgo** [comment]
^^ I agree, signaling that "normal" render options still work would be a good addition

**Comment by rmosolgo** [comment]
@garbles if/when you get a chance to update this, go ahead and remove the note about `~>1.3.0`. I'll cut a new version after merging, so I don't think it'll be necessary

**Comment by garbles** [comment]
@rmosolgo @borisrorsvort thanks for the bump. I've pushed an update.

**Comment by rmosolgo** [comment]
thanks!

**Pull request merged**
