### PR TITLE
Correct Readme installation section

### PR DESCRIPTION
**Pull request by novikserg**

### CODE REVIEW

**Comment by rmosolgo** [comment]
The install generator [creates `components.js`](https://github.com/reactjs/react-rails/blob/master/lib/generators/react/install_generator.rb#L45-L49), which that line requires.

Why should this be changed?

**Comment by novikserg** [comment]
@rmosolgo hi Robert, I used Rails 5.0.1, ruby 2.2.4 and installation instructions in readme. Generator resulted in generating `components/` folder (not file), and giving me an assets error for `require components`. As you would expect, it started working after I changed to `require_tree ./components`. So not sure if it's just Rails 5 issue or not, but it definitely exists

**Comment by akshaymohite** [comment]
@novikserg I just tried with rails `5.0.1` and react-rails `1.10.0`, and could not reproduce such issue.

I don't believe the issue would be related to ruby `2.2.4`.

Sample repository just for your reference: https://github.com/akshaymohite/rails-5-react-rails-test

**Comment by rmosolgo** [comment]
Thanks for taking another look, I guess we'll close this unless we hear someone else runs into it!

**Pull request closed without merging**
