### PR TITLE
Add es6 option to generator

### PR DESCRIPTION
**Pull request by borisrorsvort**
Here you go #316

I wanted to add some tests but basically it's just rerunning the same with another option. Should I dedupe the current one just for es6 or something else?

### CODE REVIEW

**Comment by rmosolgo** [comment]
Yes, could you add some tests for the generated output? That will help us keep from breaking things down the road :)

**Comment by borisrorsvort** [comment]
@rmosolgo Good enough?

**Comment by rmosolgo** [comment]
Sorry, I guess I should have been more specific. I think it's important to add tests for _new_ behaviors, but not important to test shared, pre-existing behaviors. In this case, it would be good to test: 

- The resulting file uses ES6 syntax (eg, checking for the `class ... extends` syntax in the result)
- The resulting file assigns propTypes after defining the class (eg, checking for `{className}.propTypes = `)
- The resulting file compiles successfully (I think `test "generates working jsx"` is sufficient for that). 

In my opinion, it's not important to repeat the tests for filename, `render` function, and `propType` since those behaviors are unchanged by the `--es6` option. 

How does that sound?

**Comment by borisrorsvort** [comment]
@rmosolgo here you go

**Comment by rmosolgo** [comment]
:money_with_wings:  Thanks, that's great!

**Comment by borisrorsvort** [comment]
:+1:

**Pull request merged**
