### PR TITLE
Get tests passing

### PR DESCRIPTION
**Pull request by jrmhaig**
### Summary

WIP

Updating to get the tests working and updated for new versions of Ruby and Rails.

### Other Information

* Update `mimemagic` in `Gemfile.lock`. The currently linked version was yanked.
* Update the Ubuntu image for Travis. Chrome depends on at least Xenial.

### To do (help needed)

The tests are failing with the `rails_5.2_no_sprockets_webpacker_*` gemfiles:

```
module.js:550
    throw err;
    ^
Error: Cannot find module 'webpack-cli/bin/config-yargs'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/reactjs/react-rails/test/dummy_webpacker3/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
Killed.
```

It look as though the way to start webpack has changed from `webpack-dev-server` to `webpack server` but I don't understand the codebase enough to know what needs updating for this.

For reference: https://github.com/webpack/webpack-dev-server/issues/2759

### CODE REVIEW

**Review by BookOfGreg — APPROVED** [review]

**Comment by justin808** [comment]
@jrmhaig can you please resolve conflicts?

We really need to switch to GH Actions.

**Comment by jrmhaig** [comment]
Sorry, I pressed the wrong button and marked this as ready for review. Conflicts are not yet resolved.

**Comment by justin808** [comment]
@jrmhaig can you help us move to Github actions? #1193.

**Comment by justin808** [comment]
@ahangarha Please take this over and make a new PR. I'll close this issue when your PR is up.

**Comment by ahangarha** [comment]
May I know the objective of this PR? We already have migrated from travis to GitHub actions (#1198) and as far as I see, all tests pass. What issue is being addressed here? Are we still trying to use travis?

**Comment by jrmhaig** [comment]
> May I know the objective of this PR? We already have migrated from travis to GitHub actions (#1198) and as far as I see, all tests pass. What issue is being addressed here? Are we still trying to use travis?

I opened this ticket over a year ago, before you migrated to Github actions. I cannot remember exactly what I was doing but I may have been trying to update it for a newer version of Rails but got stopped because I couldn't get the tests to run. I think it was somehow tied up with the `mimemagic` issue from about that time.

If the tests have moved to Github actions and are now working then obviously this can be closed.

**Comment by ahangarha** [comment]
@justin808 May you share your thought?

**Pull request closed without merging**
