### PR TITLE
react-addons-linked-state-mixin

### PR DESCRIPTION
**Pull request by SylarRuby**
Could you include this add on in your next update? It would be really useful.

### CODE REVIEW

**Comment by rmosolgo** [comment]
I see your code includes a the tilt dependency, but the issue title is the name of a React addon. Is one of those things a typo?

I'm happy to merge the tilt dependency, I wonder how it got left behind. Just making sure this is the right thing!

**Comment by SylarRuby** [comment]
@rmosolgo Hi. I'm new to pull requests so sorry for asking this question here. I want `react-addons-linked-state-mixin`. Is that possible?

**Comment by rmosolgo** [comment]
No problem, thanks for clarifying. Usually, you can report a bug or request a new feature by opening an _issue_ instead of a _pull request_. 

I expect `1.4.0` (just released today) to contain `React.addons.LinkedStateMixin`: https://github.com/reactjs/react-rails/blob/master/react-builds/addons-object.js#L4

You can activate mixins in your rails app by adding a config:

```ruby 
# in application.rb
MyApp::Application.configure do
  # ... after other configs ... 
  config.react.addons = true 
end
```

Then, restart your development server. `React.addons` should be defined in the browser. 

Does that work for you?

**Comment by SylarRuby** [comment]
I am using Rails 4 and in my application.rb I have:
```
module App
  class Application < Rails::Application
  [...]
  config.react.addons = true
  end
end
```

Is that correct @rmosolgo ?

**Comment by rmosolgo** [comment]
Yep, that looks right!

**Comment by SylarRuby** [comment]
Well then it works great. This can be closed now. Thanks

**Comment by rmosolgo** [comment]
Glad to hear it!

**Pull request closed without merging**
