### PR TITLE
Switch to GitHub Actions for testing

### LINKED ISSUE #1193: Convert from Travis to Github Actions
I don't think there's any reason to stay on Travis.

Any volunteers to help with switching to Github Actions?

### PR DESCRIPTION
**Pull request by hibachrach**
Converts from Travis to GH actions. Fixes #1193

### CODE REVIEW

**Comment by HarrisonB** [comment]
Ah I think #1150 broke some of the tests a bit more. The new version of `webpack-dev-server` has a bug because of an undeclared dependency (https://github.com/webpack/webpack-dev-server/pull/2396) and [changed the peer dependency support to be `webpack@^4.0.0`](https://github.com/webpack/webpack-dev-server/pull/1461/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R93). Not sure how to proceed

**Comment by HarrisonB** [comment]
I do think we ought to revisit the supported versions of Webpacker with this gem. I'm generally new to this sort of thing so unsure of where to cut things off (especially considering non-Shakapacker Webpacker is already retired).

**Comment by justin808** [comment]
@HarrisonB I agree with you. I opened an issue for this: https://github.com/reactjs/react-rails/issues/1199.

**Comment by justin808** [comment]
@HarrisonB any update?

**Comment by justin808** [comment]
@HarrisonB let me know when to review.

**Review by justin808 — APPROVED** [review]
LGTM

**Comment by justin808** [comment]
Thanks, @hibachrach. Let's see if this runs! We might need some followups.

**Comment by justin808** [comment]
Looks like it's running: https://github.com/reactjs/react-rails/actions

**Pull request merged**
