### PR TITLE
Run initializer blocks after :load_config_initializers

### PR DESCRIPTION
**Pull request by bogdan-dumitru**
As discussed in #550

### CODE REVIEW

**Comment by rmosolgo** [comment]
I can't think of a way to test this, but can you confirm that it solves the problem you described in #550  ?

**Comment by bogdan-dumitru** [comment]
Yeah I also was a bit disappointed in me for adding this without a spec. I can confirm that it does indeed solve it for me. I tested it from my fork without setting the helper class manually and it did set it correctly. 

But for the sake of it, let me try something. I wanna try to write a failing spec for it, open a separate PR for the failing spec just to see it fail in CI and then add the spec to this PR as well. Sounds good?

**Comment by rmosolgo** [comment]
🙌 You rock, thanks for the patch!!

**Comment by bogdan-dumitru** [comment]
Much obliged

**Pull request merged**
