### PR TITLE
polyfill clearTimeout and setTimeout for server side rendering

### PR DESCRIPTION
**Pull request by krzysiek1507**

### CODE REVIEW

**Comment by krzysiek1507** [comment]
@rmosolgo :)

**Comment by rmosolgo** [comment]
Sorry for the delay, I was trying to think if this would mess with anyone who has already polyfilled them, or if it would affect new users who don't know it's polyfilled. But I think a user polyfil would override this one, and this error is better than "undefined is not a function"!

**Comment by krzysiek1507** [comment]
@rmosolgo thanks!

**Comment by rmosolgo** [comment]
🚢  in `1.10.0`, thanks!

**Pull request merged**
