### PR TITLE
Sprockets cache expiration based on react-rails settings

### PR DESCRIPTION
**Pull request by byroot**
Followup to https://github.com/reactjs/react-rails/pull/254

See https://github.com/reactjs/react-rails/pull/254#issuecomment-98846865

cc  rmosolgo

### CODE REVIEW

**Comment by byroot** [comment]
I rebased on top of master now that #254 is merged. But it seems tests are failing. I'll find some time to fix them.

**Comment by rmosolgo** [comment]
Is `version` relatively new? It's throwing a `NoMethodError` so maybe it's not defined in some of the older Rails versions we support (3.2+)

**Comment by byroot** [comment]
No the problem is that `app.assets` is nil. Probably because the code I added is too soon in the initialization chain.

**Comment by byroot** [comment]
I just moved that code on after_initialize. It should go green now. I just keep forgetting to use `appraisal` to test my changes.

**Comment by rmosolgo** [comment]
:+1: thanks again for upstreaming!

**Pull request merged**
