### PR TITLE
feat(react.js) update to 15.3.2

### PR DESCRIPTION
**Pull request by rmosolgo**
Updated `package.json` and ran `rake react:update`

### CODE REVIEW

**Comment by rmosolgo** [comment]
> Warning: unmountComponentAtNode(): The node you're attempting to unmount was rendered by another copy of React.

What planet do I live on 😿

**Comment by Dodie324** [comment]
Any updates on this?

**Comment by rmosolgo** [comment]
It didn't work out-of-the-box, and I haven't had a chance to figure out why it thinks it was rendered by a different React version (my guess is, some change in whitespace when using Turbolinks' cache)

**Comment by Dodie324** [comment]
Hey @rmosolgo! Any luck with this? Let me know if there's anything I can do to help!

**Comment by rmosolgo** [comment]
Trying again at #646

**Pull request closed without merging**
