### PR TITLE
test: update fixture gemfile locks

### PR DESCRIPTION
**Pull request by G-Rath**
### Summary

As part of https://github.com/shakacode/shakapacker/pull/349 I have to update the lockfiles which would fail due to `mini_racer` so I had to regenerate them completely resulting in a failure because of a newer version of `selenium-webdriver` being used.

I figure ultimately this change is useful on its own because it'll impact anyone that needs to regenerate the lockfiles in future, so I might as well do a dedicated PR for it.

### Pull Request checklist

- [x] ~Add/update test to cover these changes~
- [x] ~Update documentation~
- [x] ~Update CHANGELOG file~

### CODE REVIEW

**Comment by justin808** [comment]
@G-Rath should this get merged? Looks like mainly lockfile updates.

**Comment by G-Rath** [comment]
Yup yes please!

**Comment by G-Rath** [comment]
@justin808 that also goes for the shakapacker PRs I've got open btw :)

**Comment by justin808** [comment]
Thanks @G-Rath!

**Pull request merged**
