### PR TITLE
Update react_ujs.js.erb

### PR DESCRIPTION
**Pull request by maxdignan**
More idiomatic for loops

### CODE REVIEW

**Comment by rmosolgo** [comment]
Thanks for this suggestion, can you help me understand why it is better than the existing code? Is it a style preference?

**Comment by maxdignan** [comment]
It is better because it removes the instantiation of a new variable for each cycle of the loop (var node = index in nodes). Instead now, there is no variable instantiation, and instead just merely the pointer is passed into each cycle of the loops for the respective index in nodes. On top of this, does not expose an index variable, which would, to developers just entering the project, imply that some math will be done with this index variable. But in reality, this does not occur. This commit uses better practices that are better not just from performance, but also readability.

**Comment by mchristen** [comment]
The performance gains are dubious at best given the usage of this code, It's mostly run once per page load. Also, if you were to look into the implementation of forEach I would imagine it's going to be something similar to what the for loop is doing manually, so you're not really saving anything, just moving the logic to a place where a developer can't see it.

I would also argue that the code is not more readable, first of all you need to understand what 'call' is doing and why there is a seemingly random empty array being used. 

I think this is a case of: "If it ain't broke, don't fix it."

**Comment by rmosolgo** [comment]
> I think this is a case of: "If it ain't broke, don't fix it."

Yep, that's my instinct too. 

If it turns out that refactoring this code would improve browser support or fix a bug, let's do it, but otherwise, I think it's better to stick with what has worked well so far!

**Pull request closed without merging**
