### PR TITLE
fix(prerender) accept string props

### PR DESCRIPTION
**Pull request by rmosolgo**
My first API was shoving `prerender:` into the props hash, but obviously that doesn't work if props isn't a hash! 

So instead, pass `prerender_options` along through the ServerRendering pipeline. In theory, a render could take any options. 

`SprocketsRenderer` looks for `:static`, to use `React.renderToStaticMarkup`

### CODE REVIEW

**Comment by mchristen** [comment]
I tried this out and I'm running into an issue with sprockets now.

In particular 

    Asset was linked to from an alias rather than its exact path. Alias resolving may not be available in production.
    Use "react.js" instead of "development-with-addons/react.js"

being thrown from

    #<Class:0x007fee7182f188>#asset_digest_path
    sprockets-rails (2.3.1) lib/sprockets/rails/helper.rb, line 134

This is kind of confusing because it is a call to //= require react that is raising the exception

**Comment by rmosolgo** [comment]
wow, is there any more stack trace to that? 

If it's booting a renderer and _trying_ to prerender, I guess it's coming from here: https://github.com/reactjs/react-rails/blob/master/lib/react/server_rendering/sprockets_renderer.rb#L11

But why would it work fine in the asset pipeline but not in prerender?

**Comment by rmosolgo** [comment]
Reproduced on Sprockets 2.8. Oh, I misunderstood: it's coming from the asset pipeline, _not_ from prerender!

**Comment by mchristen** [comment]
Correct, this is for the client side JS file loaded in the rails layout. 

     sprockets-rails (2.3.1) lib/sprockets/rails/helper.rb:134:in `asset_digest_path'
     sprockets-rails (2.3.1) lib/sprockets/rails/helper.rb:85:in `compute_asset_path'
     actionview (4.2.0) lib/action_view/helpers/asset_url_helper.rb:135:in `asset_path'  
     sprockets-rails (2.3.1) lib/sprockets/rails/helper.rb:100:in `asset_path'
     actionview (4.2.0) lib/action_view/helpers/asset_url_helper.rb:245:in `javascript_path'
     sprockets-rails (2.3.1) lib/sprockets/rails/helper.rb:153:in `block (2 levels) in javascript_include_tag'
     sprockets-rails (2.3.1) lib/sprockets/rails/helper.rb:152:in `block in javascript_include_tag'
     sprockets-rails (2.3.1) lib/sprockets/rails/helper.rb:149:in `javascript_include_tag'
     app/views/layouts/application.html.haml:33:in `_app_views_layouts_application_html_haml___1984877869646349502_70331041908800'

**Comment by rmosolgo** [comment]
Looks like this was touched recently in `sprockets-rails`, double-checking here: https://github.com/rails/sprockets-rails/issues/247#issuecomment-103162751

I didn't notice it before because I was on sprockets 3 :S

**Comment by rmosolgo** [comment]
@mchristen sounds like a sprockets-rails 2.3.1 issue, see this comment: https://github.com/rails/sprockets-rails/issues/247#issuecomment-103666873

**Comment by mchristen** [comment]
It definitely occurs prior to that version as well(at least as early as 2.2.4). When I first ran into the error I came across that issue on sprocket-rails and saw that code was touched with 2.3.1 so I updated to that version to see if the problem went away. When the problem persisted is when I made the comment above. 

Either way it looks like there will be a fix shortly, thanks for the work!

**Comment by rmosolgo** [comment]
aiiiyayay well the regression test for this particular issue passes, so i'm gonna go for it

**Comment by rmosolgo** [comment]
@mchristen they've shipped `sprockets-rails` 2.3.2 & I'm able to use them together:

```
~/code/check-ins $ bundle show | grep 'sprockets\|react'
  * react-rails (1.0.0 9a4f6ab)
  * sprockets (2.12.3)
  * sprockets-rails (2.3.2)
```

Please let me know if you can confirm/deny, if we're clear with the latest sprockets-rails I want to get ready for a new version release :D

**Pull request merged**
