### PR TITLE
#639 Pass pre-render options to callback functions

### PR DESCRIPTION
**Pull request by prikha**
Changes:

- Refactor a bit base renderer
- Refactor `SprocketsRenderer` to preserve custom prerender options

#639

### CODE REVIEW

**Comment by rmosolgo** [comment]
This patch looks great, but can you add a test to demonstrate the changed behavior?

Sorry about the CI crash. I've updated `.travis.yml`, do you mind rebasing on latest master?

**Comment by prikha** [comment]
Yepp, I`ll try something out

**Comment by prikha** [comment]
Done that(https://travis-ci.org/reactjs/react-rails/builds/180025155), however the build on Travis is extremely slow. Why would you keep 

```
allow_failures:
    - rvm: jruby-9.0.1.0
```

which always take 10 minutes and always fail?

**Comment by rmosolgo** [comment]
I agree that the JRuby situation is not good! I think we moved them into "allow failures" for Rails 5, since no JRuby version supported Rails 5 at that time. 

It looks like they timeout now :( It would be nice to fix those, because I think we _should_ support JRuby.

Thanks for this improvement! It will make custom renderers more powerful!

**Comment by rmosolgo** [comment]
🚢  in `1.10.0`, thanks!

**Pull request merged**
