### PR TITLE
Upgrade react-source to 0.12.2

### PR DESCRIPTION
**Pull request by jordanstephens**
Upgrading react-source to 0.12.2

Tests were failing when expecting a single quoted string in transformed JSX. It looks like this can be traced back to facebook/react@eddbb0c, so I'm updating the expectation to a double-quoted string—see 71a01bc.

### CODE REVIEW

**Comment by rmosolgo** [comment]
I thought leaving out the minor version was be design -- it installs the latest minor version by default, right?

**Comment by zpao** [comment]
`gem install react-rails` uses the 0.12.x.y release, which does specify patch versions. Only the stable releases have been published. `master` however is more fluid and uses the latest instead of locking because we don't really have version numbers there. If you did this against the 0.12 branch (https://github.com/reactjs/react-rails/tree/0.12) then I would go ahead and merge this in but we probably shouldn't do this for master.

Want to do this against the other branch and then I'll publish the v0.12.2.0 gem.

**Comment by jordanstephens** [comment]
Thanks @zpao, I'll open a new PR on the 0.12 branch.

Before I close this, I'm still a little bit confused:

> master however is more fluid and uses the latest instead of locking 

I believe the current dependency definition on master *is* locked (on 0.12.0):

`s.add_dependency 'react-source', '0.12'`

I just double checked the version in my Gemfile.lock after bundling from master and I am indeed seeing `react-source (0.12.0)`.

Don't we want to use the following on master instead?

`s.add_dependency 'react-source', '~> 0.12'`

Thanks again!

**Comment by zpao** [comment]
Yea, I was actually going to ask. I think you're right that we want the `~>`. I think that's safe to go ahead and do.

**Comment by jordanstephens** [comment]
Just rebased this branch to include the `~>`.

Thanks @zpao!

**Comment by rmosolgo** [comment]
Nice!

**Pull request merged**
