### PR TITLE
Remove window variable from ExecJS environment

### PR DESCRIPTION
**Pull request by NGMarmaduke**
Fixes https://github.com/reactjs/react-rails/issues/614

Defining window on the server can cause major issues when using 3rd party libraries that perform type of checks on the window variable to detect the presence of a browser environment.

A common check for presence of the browser is:

``` javascript
if (typeof window !== 'undefined') { 
  // do browser stuff
}
```

This PR removes the requirement for window to exist on the server. It will however be a breaking change for applications that implicitly expect the existence of window in all javascript environments. 

The definition of window on the server could potentially be made a configuration option to mitigate errors.

~~This PR also updates React to version 15.3.2~~

### CODE REVIEW

**Comment by NGMarmaduke** [comment]
Looks like running into the same error as https://github.com/reactjs/react-rails/pull/611

**Comment by NGMarmaduke** [comment]
Removed the update to React

**Comment by rmosolgo** [comment]
I think this is Ok, but we need to document the change so that people who currently _depend_ on window (using it as the global namespace) know how to upgrade. 

I checked coffeescript, it looks like it compiles to something compatible: 

```coffee
@test = false 
```

to 

```js
(function() { 
  this.test = false 
}).call(this)
```

(I thought it might use `window` as `@`, but looks like not)

**Comment by NGMarmaduke** [comment]
Indeed, I'm attempting to apply this update to our app to see if its even feasible / sensible to make this change

**Comment by rmosolgo** [comment]
How did it go applying this to your app?

**Comment by rmosolgo** [comment]
I hope it went ok :P But I agree, making server render _pretend_ to be a browser env only makes it worse down the line.

**Comment by rmosolgo** [comment]
🚢  in `1.10.0`, thanks!

**Comment by dbackeus** [comment]
Not actually sure how to fix the errors we get after upgrading to `1.10.0`:
```
     Failure/Error: <%= react_component "ComponentName", {
     
     ActionView::Template::Error:
       ReferenceError: window is not defined
     # (execjs):44062:3
     # (execjs):44064:2
```

The components we use do not reference `window` explicitly as far as I can see (but are defined as `@ComponentName = React.createClass(...)`).

The CHANGELOG mentions manually adding `window = this` but not sure where to do that?

**Comment by rmosolgo** [comment]
@dbackeus Do those errors come from server rendering? 

Do you have a server-rendering manifest (some file that requires all the components for server rendering)? If so, you can add it to that file, for example: 

```js 
//= require components 
// polyfill `window` variable for server rendering environments:
var window = this 
```

If that doesn't help, can you share the lines of code that reference `window`? A better (or earlier) polyfill may be needed

**Comment by piratefsh** [comment]
FYI I had the same `window is not defined` issue and tried to set `var window = this` after the components were required but that still gave the error. What worked was to set `window` before the React was required. In my case, React was required in my `react_app` file.

e.g.

```
// polyfill for prerendering. must be set before requiring react
var window = this;

//= require react_app
```

**Comment by piratefsh** [comment]
Since `window` is needed to even load React, shouldn't this be mentioned in the README setup?

**Pull request merged**
