### PR TITLE
add support for IE8 without jQuery

### PR DESCRIPTION
**Pull request by AndreaMaggi**
quick fix for IE8 without jQuery...which you probably wont/cant have with server side render

### CODE REVIEW

**Comment by tosbourn** [comment]
:+1:

**Comment by rmosolgo** [comment]
wow, ok! could you add a little explanatory comment so we don't remove it in the future?  eg `// support IE8 without jQuery`

**Comment by AndreaMaggi** [comment]
Sure @rmosolgo will update it now

**Comment by rmosolgo** [comment]
Cool, thanks! :tada:

**Pull request merged**
