### PR TITLE
Update React to 15.2.1

### PR DESCRIPTION
**Pull request by mikesea**

### CODE REVIEW

**Comment by rmosolgo** [comment]
Huhhhh

```
/home/travis/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:89:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'turbolinks'. (Bundler::GemRequireError)
Gem Load Error is: undefined method `assets' for #<Rails::Engine::Configuration:0x000000022ba5a0>
Backtrace for gem load error is:
/home/travis/build/reactjs/react-rails/gemfiles/vendor/bundle/ruby/2.3.0/gems/railties-3.2.22.2/lib/rails/railtie/configuration.rb:85:in `method_missing'
/home/travis/build/reactjs/react-rails/gemfiles/vendor/bundle/ruby/2.3.0/gems/turbolinks-5.0.0/lib/turbolinks.rb:17:in `<class:Engine>'
/home/travis/build/reactjs/react-rails/gemfiles/vendor/bundle/ruby/2.3.0/gems/turbolinks-5.0.0/lib/turbolinks.rb:14:in `<module:Turbolinks>'
/home/travis/build/reactjs/react-rails/gemfiles/vendor/bundle/ruby/2.3.0/gems/turbolinks-5.0.0/lib/turbolinks.rb:5:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
/home/travis/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
/home/travis/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
/home/travis/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
/home/travis/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
```

Turbolinks 5 with Rails 3.2 ... maybe we could just _exclude_ it!

**Comment by mikesea** [comment]
Something weird is happening because the Rails 5, no Sprockets build also failed. I'm looking into it.

**Comment by mikesea** [comment]
Travis should ignore the Rails 3.2 failures now. I also encountered an issue with one of the Rails 5 builds, which should be fixed.

The `rails_5_no_sprockets.gemfile` tries to test behavior of the gem without Sprockets. Turbolinks 5, however, seems to have an implicit dependency on Sprockets. The line here: https://github.com/turbolinks/turbolinks-rails/blob/master/lib/turbolinks.rb#L17 will try to add the turbolinks source to the list of precompiled assets, but `config.assets` is only defined when `sprockets/railtie` is required. To workaround that, I added `require: false` to the turbolinks dependency in the rails_5_no_sprockets.gemfile` Gemfile.

**Comment by mikesea** [comment]
@rmolsogo Travis build is passing now, thanks!

**Comment by mikesea** [comment]
@rmosolgo ping :)

**Comment by rmosolgo** [comment]
:+1: I guess we _could_ drop official Rails 3 support soon anyways, although considering some folks even asked for _Rails 2_, I'm sure there are plenty of Rails 3 users out there!

**Pull request merged**
