### PR TITLE
fixed insert many require react when the file has many require_tree

### PR DESCRIPTION
**Pull request by towonzhou**
done

### CODE REVIEW

**Comment by towonzhou** [comment]
Does not need this?

**Comment by rmosolgo** [comment]
Since this doesn't have a test case, I want to read up `inject_into_file` before I merge it. 

If you'd like to help me, you could add a test case which demonstrates the new behavior!

**Comment by rmosolgo** [comment]
I tried this out locally:

- First, I made an application.js which included only:

  ```
  //= require_tree ./application 
  //= require_tree ./something_else
  ```

- Using react-rails 1.2.0, I ran `bundle exec rails g react:install`. 
- I observed the unwanted behavior. It added the react stuff to `application.js` twice: 
  ```
  //= require react
  //= require react_ujs
  //= require components
  //= require_tree ./application
  //= require react
  //= require react_ujs
  //= require components
  //= require_tree ./something_else
  ```

- I reverted application.js to its original state. 
- I pointed at this branch and `bundle install`ed 
  
  ```
  Using react-rails 1.4.1 (was 1.2.0) from git://github.com/towonzhou/react-rails.git (at master)
  ```
- I ran `bundle exec rails g react:install`
- I got the desired behavior. `application.js` contained: 

  ```
  //= require react
  //= require react_ujs
  //= require components
  //= require_tree ./application
  //= require_tree ./something_else
  ```

**Comment by rmosolgo** [comment]
:confetti_ball:  thank you for this fix!

**Comment by towonzhou** [comment]
@rmosolgo it's my pleasure.

**Pull request merged**
