### PR TITLE
Pick-and-choose addons with Sprockets directives

### PR DESCRIPTION
**Pull request by danott**
The desire for this feature is mentioned in the comments of #447, which is mentioned in the 2.0.0 issue (#448).

With these changes, a consumer of react-rails can now pick-and-choose which add-ons they'd like to have using Sprockets require directives.

### CODE REVIEW

**Comment by rmosolgo** [comment]
:+1: So nice! I see this includes an update to 0.14.6 too, right? Thanks for that!

**Comment by dezmathio** [comment]
@danott @rmosolgo Does this PR only affect official React Addons or could this be used for any component? even things specifically installed via npm ?

**Comment by rmosolgo** [comment]
Only official react addons!

**Comment by rmosolgo** [comment]
Oops, I didn't realize til now -- some of these addons have `require("react")` and the like, which causes those dependencies to be bundled in by webpack. As a result, the addon files may also include a lot of duplicated framework code and be much larger than _just_ the addon! 

I think that's why some of them are so big:

image


I noticed this because I'm working with `ReactDOMServer` and it's doing the same thing! Hmmm...

**Comment by valff** [comment]
Such duplication causes a lot of react errors:

> Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's 'render' method, or **you have multiple copies of React loaded** (details: https://fb.me/react-refs-must-have-owner).

**Pull request merged**
