### PR TITLE
include module-related code when generating for webpack

### PR DESCRIPTION
**Pull request by rmosolgo**

### CODE REVIEW

**Comment by rmosolgo** [comment]
Same Rails 5.1 failures

**Comment by ViXP** [comment]
Please, fix the --coffee generator too

**Comment by rmosolgo** [comment]
@vixp if you've noticed a bug or if you have a feature request, please open an issue!

**Comment by ViXP** [comment]
--coffee generator must include this
`"module.exports = @#{component_name}"`
too

**Pull request merged**
